### ISSUE TITLE
errors in ffmpeg

### ISSUE THREAD

**Issue by lelikg** [ethand91/mediasoup3-record-demo#10] opened 2020-04-05 10:01 UTC
Hi, perhaps you can help me understand the cause of the issues I am having?
When streaming from chrome using h264, ffmpeg outputs the following errors

```
Error while decoding stream #0:0: Invalid data found when processing input
```

```
[h264 @ 0x560aaea4a940] concealing 2468 DC, 2468 AC, 2468 MV errors in P frame
```

```
pipe:0: corrupt decoded frame in stream 0
```
```
[h264 @ 0x560aaeaee1c0] non-existing PPS 31 referenced
[h264 @ 0x560aaeaee1c0] decode_slice_header error
```

**Comment by lelikg** [comment] 2020-04-05 10:21
additionaly I am getting this error quite a lot:
`on-monotonous DTS in output stream 0:1; previous: 9109290, current: 9105270; changing to 9109291. This may result in incorrect timestamps in the output file.`

**Comment by ethand91** [comment] 2020-04-06 02:19
Hello, can you share the ffmpeg command/arguments you are using?

**Comment by lelikg** [comment] 2020-04-06 08:15
Sure, here it is
```
ffmpeg -analyzeduration 2147483647 -probesize 2147483647 -hide_banner -loglevel info -protocol_whitelist pipe,rtp,udp -max_delay 0 -f sdp -i pipe:0 -r 24 -x264opts threads=12:subme=6:keyint=24:bframes=2:min-keyint=24:ref=3:b-pyramid=0:b-adapt=0:no-scenecut -c:v:0 libx264 -b:v:0 2944k -c:a:0 aac -s:v:0 1280x720 -b:a:0 128k -preset:0 fast -profile:v:0 main -level:v:0 4.1 -c:v:1 libx264 -b:v:1 1104k -c:a:1 aac -s:v:1 854x480 -b:a:1 96k -preset:1 fast -profile:v:1 main -level:v:1 3.1 -c:v:2 libx264 -b:v:2 250k -c:a:2 aac -s:v:2 426x240 -b:a:2 64k -preset:2 fast -profile:v:2 main -level:v:2 3.1 -sn -ac 2 -hls_time 2 -hls_list_size 5 -start_number 1 -threads 4 -thread_type slice -map 0:v -map 0:a -map 0:v -map 0:a -map 0:v -map 0:a -f hls -var_stream_map v:0,a:0,name:720p v:1,a:1,name:480p v:2,a:2,name:240p -master_pl_name master.m3u8 -hls_playlist_type event -hls_segment_filename /streams/e5a21ef7-e28b-46ac-bcef-6e67b0021d91/%v/segment_%03d.ts /streams/e5a21ef7-e28b-46ac-bcef-6e67b0021d91/%v/index.m3u8
```

**Comment by ethand91** [comment] 2020-04-07 10:01
Hello,
Sorry I can't really help much if the problem is unrelated to the project. 
From a glance it seems that there is something wrong with the input of the stream.

To my knowledge MV errors in P frame is fixed in recent versions of ffmpeg, if your are using the latest ffmpeg and it still occurs, then you may want to ask on ffmpeg's trac:
http://trac.ffmpeg.org/

**Closed by ethand91** 2020-04-07 10:01 UTC
